# Generated by Django 5.0.6 on 2025-12-25 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jobapplication",
            old_name="applied_at",
            new_name="created_at",
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("hired", "Hired"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.job"
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="phone",
            field=models.CharField(max_length=20),
        ),
    ]
