# Generated by Django 5.0.6 on 2025-12-25 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rename_applied_at_jobapplication_created_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jobapplication",
            old_name="created_at",
            new_name="applied_at",
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="core.job",
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="phone",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("applied", "Applied"),
                    ("hired", "Hired"),
                    ("rejected", "Rejected"),
                ],
                default="applied",
                max_length=20,
            ),
        ),
    ]
