# Generated by Django 5.0.6 on 2025-12-25 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_rename_created_at_jobapplication_applied_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobapplication",
            name="message",
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="status",
            field=models.CharField(default="applied", max_length=20),
        ),
    ]
