# Generated by Django 5.0.6 on 2025-12-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_jobapplication_message_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("applied", "Applied"),
                    ("hired", "Hired"),
                    ("rejected", "Rejected"),
                ],
                default="applied",
                max_length=20,
            ),
        ),
    ]
