# Generated by Django 5.0.6 on 2026-01-02 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_kycprofile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="kycprofile",
            old_name="submitted_at",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="kycprofile",
            name="document_file",
        ),
        migrations.RemoveField(
            model_name="kycprofile",
            name="document_type",
        ),
        migrations.RemoveField(
            model_name="kycprofile",
            name="status",
        ),
        migrations.RemoveField(
            model_name="kycprofile",
            name="verified_at",
        ),
        migrations.AddField(
            model_name="kycprofile",
            name="is_verified",
            field=models.BooleanField(default=True),
        ),
    ]
